name: artshopDirect
recipe: drupal9
config:
  drush: "*"
  webroot: .
  services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  phpmyadmin:
    - phpmyadmin.drupal9.lndo.site
